/**
 * Public entry point for the `@cosyte/x12` package. Phase 1 lands the
 * envelope decoder (ISA / GS / GE / IEA + delimiter detection); Phase 2+
 * adds segment/element/composite decode, the warning-code registry
 * expansion, and the public `defineLoopSpec`. Per-transaction helpers
 * (`get835`, `get837Claims`, ...) arrive in Phases 4+.
 */

/**
 * Library version string, synced with `package.json#version` at build
 * time by downstream phases. Exported now so consumers (and the
 * type-check pipeline) have at least one symbol to resolve through the
 * `exports` map.
 *
 * @example
 * ```ts
 * import { VERSION } from "@cosyte/x12";
 * console.log(VERSION);
 * ```
 */
export const VERSION: string = "0.0.0";

// Phase 1 — envelope parser surface.
export { parseX12 } from "./parser/index.js";
export { detectDelimiters, DELIMITER_POSITIONS, ISA_MIN_LENGTH } from "./parser/delimiters.js";
export { FATAL_CODES, X12ParseError } from "./parser/errors.js";
export type { X12FatalCode } from "./parser/errors.js";
export {
  WARNING_CODES,
  controlNumberMismatch,
  danglingReleaseChar,
  groupCountMismatch,
  hlParentLevelInvalid,
  hlParentMismatch,
  missingGe,
  missingIea,
  missingRequiredLoop,
  missingSe,
  pre005010,
  remitBalanceMismatch,
  segmentCountMismatch,
  trailingGarbage,
  transactionCountMismatch,
  unexpectedSegment,
  unknown837Variant,
  unknownCarc,
  unknownClaimStatus,
  unknownClaimStatusCategory,
  unknownHiQualifier,
  unknownMaintenanceType,
  unknownRarc,
} from "./parser/warnings.js";
export type { X12ParseWarning, X12WarningCode } from "./parser/warnings.js";
export type {
  Delimiters,
  GeSegment,
  GsSegment,
  IeaSegment,
  IsaSegment,
  OnWarningCallback,
  Ta1Segment,
  X12FunctionalGroup,
  X12Interchange,
  X12ParseOptions,
  X12Position,
  X12TransactionSet,
} from "./parser/types.js";

// Phase 2 — segment / element / composite / repetition decode surface.
export { escapeRelease, RELEASE_CHAR, unescapeRelease } from "./parser/release.js";
export {
  collectElementValues,
  componentOptional,
  decodeSegment,
  elementDecimal,
  elementDecimalOrZero,
  elementOptional,
  elementValue,
  getAllSegmentValues,
  getSegmentValue,
} from "./parser/segment.js";
export type { X12Segment } from "./parser/segment.js";

// Phase 2 — loop-spec authoring surface (dogfooded by built-in transaction
// specs in Phases 3+).
export { defineLoopSpec, LoopSpecDefinitionError } from "./loops/define.js";
export type { DefineLoopSpecInput } from "./loops/define.js";
export type { LoopMax, LoopSegmentSpec, LoopSpec, LoopUsage } from "./loops/types.js";

// Phase 4 — money + bundled code-list snapshots used by 835.
export { X12Decimal } from "./decimal.js";
export {
  CARC,
  CLAIM_ADJUSTMENT_GROUP_CODES,
  CLAIM_STATUS_CATEGORY_CODES,
  CLAIM_STATUS_CODES,
  CLP_STATUS,
  MAINTENANCE_TYPE_CODES,
  RARC,
  HI_QUALIFIERS,
  SERVICE_TYPE_CODES,
  isClaimAdjustmentGroupCode,
  isDiagnosisQualifier,
  isProcedureQualifier,
  lookupCarc,
  lookupClaimStatus,
  lookupClaimStatusCategory,
  lookupClpStatus,
  lookupMaintenanceType,
  lookupRarc,
  lookupServiceType,
  resolveHiQualifier,
  type ClaimAdjustmentGroupCode,
  type CodeListEntry,
  type CodeListMeta,
  type CodeListSnapshot,
  type X12HiCategory,
  type X12HiCodeSystem,
  type X12HiQualifier,
} from "./code-lists/index.js";

// Phase 4 — 835 Healthcare Claim Payment/Advice (ERA) surface (TR3 005010X221A1).
export {
  REMIT_835_BUILD_ERROR_CODES,
  REMIT_835_LOOP_1000A,
  REMIT_835_LOOP_1000B,
  REMIT_835_LOOP_2000,
  REMIT_835_LOOP_2100,
  REMIT_835_LOOP_2110,
  Remit835BuildError,
  build835,
  checkClaimBalance,
  checkRemitTotalBalance,
  checkServiceLineBalance,
  get835,
  type Build835AddressSpec,
  type Build835AdjustmentSpec,
  type Build835AmountSpec,
  type Build835ClaimSpec,
  type Build835ContactSpec,
  type Build835EnvelopeSpec,
  type Build835PartySpec,
  type Build835PaymentSpec,
  type Build835PersonSpec,
  type Build835ProviderAdjustmentSpec,
  type Build835ProviderSpec,
  type Build835ReferenceSpec,
  type Build835RemarkSpec,
  type Build835ServiceLineSpec,
  type Build835Spec,
  type Build835TraceSpec,
  type Remit835BuildErrorCode,
  type X12RemitAddress,
  type X12RemitAdjustment,
  type X12RemitAmount,
  type X12RemitClaim,
  type X12RemitContact,
  type X12RemitParty,
  type X12RemitPaymentHeader,
  type X12RemitPerson,
  type X12RemitProvider,
  type X12RemitProviderAdjustment,
  type X12RemitReference,
  type X12RemitRemark,
  type X12RemitServiceLine,
  type X12RemitTrace,
  type X12Remittance,
} from "./transactions/remit/index.js";

// Phase 5 — 837 Healthcare Claim surface (TR3s 005010X222A2 / X223A3 / X224A2).
export {
  CLAIM_837D_LOOP_2000A,
  CLAIM_837D_LOOP_2300,
  CLAIM_837D_LOOP_2400,
  CLAIM_837I_LOOP_2000A,
  CLAIM_837I_LOOP_2300,
  CLAIM_837I_LOOP_2400,
  CLAIM_837P_LOOP_2000A,
  CLAIM_837P_LOOP_2300,
  CLAIM_837P_LOOP_2400,
  CLAIM_837P_LOOP_2410,
  CLAIM_837_LOOP_1000A,
  CLAIM_837_LOOP_1000B,
  CLAIM_837_LOOP_2010AA,
  CLAIM_837_LOOP_2010BA,
  CLAIM_837_LOOP_2010BB,
  CLAIM_837_LOOP_2010CA,
  CLAIM_837_LOOP_2430,
  CLAIM_837_BUILD_ERROR_CODES,
  Claim837BuildError,
  HL_LEVEL_CODES,
  NM1_QUALIFIERS,
  build837D,
  build837I,
  build837P,
  get837Claims,
  type Build837AddressSpec,
  type Build837AdjudicationSpec,
  type Build837AdjustmentSpec,
  type Build837AmountSpec,
  type Build837BillingProviderSpec,
  type Build837ClaimSpec,
  type Build837ContactSpec,
  type Build837DateSpec,
  type Build837DrugSpec,
  type Build837EntitySpec,
  type Build837EnvelopeSpec,
  type Build837HiCodeSpec,
  type Build837NoteSpec,
  type Build837OtherSubscriberSpec,
  type Build837PatientSpec,
  type Build837ReferenceSpec,
  type Build837ServiceLineBaseSpec,
  type Build837ServiceLineDentalSpec,
  type Build837ServiceLineInstitutionalSpec,
  type Build837ServiceLineProfessionalSpec,
  type Build837ServiceLineSpec,
  type Build837Spec,
  type Build837SubscriberInfoSpec,
  type Build837SubscriberSpec,
  type Build837ToothSpec,
  type Claim837BuildErrorCode,
  type X12Claim,
  type X12Claim837Variant,
  type X12ClaimAddress,
  type X12ClaimAmount,
  type X12ClaimContact,
  type X12ClaimDate,
  type X12ClaimEntity,
  type X12ClaimHiCode,
  type X12ClaimMember,
  type X12ClaimNote,
  type X12ClaimReference,
  type X12HierarchicalLevel,
  type X12LineAdjudication,
  type X12LineDrug,
  type X12OtherSubscriber,
  type X12SubscriberInfo,
  type X12ToothInformation,
  type X12_837ServiceLine,
  type X12_837ServiceLineDental,
  type X12_837ServiceLineInstitutional,
  type X12_837ServiceLineProfessional,
  type X12_837Submission,
} from "./transactions/claim/index.js";

// Phase 6 — 271 Health Care Eligibility Benefit Response surface (TR3 005010X279A1).
export {
  ELIGIBILITY_271_BUILD_ERROR_CODES,
  ELIGIBILITY_271_LOOP_2000A,
  ELIGIBILITY_271_LOOP_2000B,
  ELIGIBILITY_271_LOOP_2000C,
  ELIGIBILITY_271_LOOP_2000D,
  ELIGIBILITY_271_LOOP_2100C,
  ELIGIBILITY_271_LOOP_2100D,
  ELIGIBILITY_271_LOOP_2110,
  Eligibility271BuildError,
  build271,
  get271Eligibility,
  type Build271AddressSpec,
  type Build271BenefitSpec,
  type Build271DateSpec,
  type Build271DependentSpec,
  type Build271EntitySpec,
  type Build271EnvelopeSpec,
  type Build271InformationReceiverSpec,
  type Build271InformationSourceSpec,
  type Build271MemberSpec,
  type Build271ReferenceSpec,
  type Build271ServiceTypeSpec,
  type Build271Spec,
  type Build271SubscriberSpec,
  type Build271TraceSpec,
  type Eligibility271BuildErrorCode,
  type X12Eligibility,
  type X12EligibilityAddress,
  type X12EligibilityBenefit,
  type X12EligibilityDate,
  type X12EligibilityDependent,
  type X12EligibilityEntity,
  type X12EligibilityMember,
  type X12EligibilityReference,
  type X12EligibilityServiceType,
  type X12EligibilitySubscriber,
  type X12EligibilityTrace,
} from "./transactions/eligibility/index.js";

// Phase 6 — 277 / 277CA Claim Status surface (TR3s 005010X212 / X214).
export {
  CLAIM_STATUS_277_BUILD_ERROR_CODES,
  ClaimStatus277BuildError,
  STATUS_277_LOOP_2000A,
  STATUS_277_LOOP_2000B,
  STATUS_277_LOOP_2000C,
  STATUS_277_LOOP_2000D,
  STATUS_277_LOOP_2000E,
  STATUS_277_LOOP_2200,
  STATUS_277_LOOP_2220,
  build277,
  build277CA,
  get277CADisposition,
  get277Status,
  type Build277ClaimSpec,
  type Build277DateSpec,
  type Build277DependentSpec,
  type Build277EntitySpec,
  type Build277EnvelopeSpec,
  type Build277InformationReceiverSpec,
  type Build277InformationSourceSpec,
  type Build277MemberSpec,
  type Build277ProviderSpec,
  type Build277ReferenceSpec,
  type Build277ServiceLineSpec,
  type Build277Spec,
  type Build277StatusCodeSpec,
  type Build277StatusSpec,
  type Build277SubscriberSpec,
  type Build277TraceSpec,
  type ClaimStatus277BuildErrorCode,
  type X12ClaimStatus,
  type X12ClaimStatusResponse,
  type X12ServiceLineStatus,
  type X12StatusCode,
  type X12StatusDate,
  type X12StatusEntity,
  type X12StatusInfo,
  type X12StatusMember,
  type X12StatusReference,
  type X12StatusTrace,
} from "./transactions/status/index.js";

// Phase 7 — 820 Premium Payment surface (TR3 005010X218).
export {
  PREMIUM_820_LOOP_1000A,
  PREMIUM_820_LOOP_1000B,
  PREMIUM_820_LOOP_2000A,
  PREMIUM_820_LOOP_2100A,
  PREMIUM_820_LOOP_2300A,
  PREMIUM_820_LOOP_2310A,
  PREMIUM_820_BUILD_ERROR_CODES,
  Premium820BuildError,
  build820,
  get820Payments,
  type Build820AddressSpec,
  type Build820AdjustmentSpec,
  type Build820DateSpec,
  type Build820EntitySpec,
  type Build820EnvelopeSpec,
  type Build820OpenItemSpec,
  type Build820PartySpec,
  type Build820PaymentSpec,
  type Build820PersonSpec,
  type Build820ReferenceSpec,
  type Build820RemittanceSpec,
  type Build820Spec,
  type Build820TraceSpec,
  type Premium820BuildErrorCode,
  type X12PremiumAddress,
  type X12PremiumAdjustment,
  type X12PremiumDate,
  type X12PremiumEntity,
  type X12PremiumOpenItem,
  type X12PremiumParty,
  type X12PremiumPaymentHeader,
  type X12PremiumPayments,
  type X12PremiumPerson,
  type X12PremiumReference,
  type X12PremiumRemittance,
  type X12PremiumTrace,
} from "./transactions/premium/index.js";

// Phase 7 — 834 Benefit Enrollment and Maintenance surface (TR3 005010X220A1).
export {
  ENROLLMENT_834_LOOP_1000A,
  ENROLLMENT_834_LOOP_1000B,
  ENROLLMENT_834_LOOP_2000,
  ENROLLMENT_834_LOOP_2100A,
  ENROLLMENT_834_LOOP_2300,
  ENROLLMENT_834_LOOP_2320,
  ENROLLMENT_834_BUILD_ERROR_CODES,
  Enrollment834BuildError,
  build834,
  get834Enrollments,
  get834Header,
  type Build834AddressSpec,
  type Build834AmountSpec,
  type Build834CoordinationOfBenefitsSpec,
  type Build834CoverageSpec,
  type Build834DateSpec,
  type Build834EnvelopeSpec,
  type Build834HeaderSpec,
  type Build834MemberNameSpec,
  type Build834MemberSpec,
  type Build834PartySpec,
  type Build834ReferenceSpec,
  type Build834Spec,
  type Enrollment834BuildErrorCode,
  type X12CoordinationOfBenefits,
  type X12Enrollment,
  type X12EnrollmentAddress,
  type X12EnrollmentAmount,
  type X12EnrollmentDate,
  type X12EnrollmentHeader,
  type X12EnrollmentMember,
  type X12EnrollmentParty,
  type X12EnrollmentReference,
  type X12HealthCoverage,
} from "./transactions/enrollment/index.js";

// Phase 7 — 278 Health Care Services Review surface (request TR3 005010X217 /
// response TR3 005010X216).
export {
  AUTH_278_BUILD_ERROR_CODES,
  AUTH_278_LOOP_2000A,
  AUTH_278_LOOP_2000B,
  AUTH_278_LOOP_2000C,
  AUTH_278_LOOP_2000D,
  AUTH_278_LOOP_2000E,
  AUTH_278_LOOP_2000F,
  ServicesReview278BuildError,
  build278Request,
  build278Response,
  get278Request,
  get278Response,
  type Build278DateSpec,
  type Build278DecisionSpec,
  type Build278DependentSpec,
  type Build278DiagnosisSpec,
  type Build278EntitySpec,
  type Build278EnvelopeSpec,
  type Build278HeaderSpec,
  type Build278MemberSpec,
  type Build278ReferenceSpec,
  type Build278ReviewSpec,
  type Build278Spec,
  type Build278SubscriberSpec,
  type Build278TraceSpec,
  type ServicesReview278BuildErrorCode,
  type X12AuthDate,
  type X12AuthDiagnosis,
  type X12AuthEntity,
  type X12AuthHeader,
  type X12AuthMember,
  type X12AuthReference,
  type X12AuthTrace,
  type X12ReviewDecision,
  type X12ServiceReview,
  type X12ServicesReview,
} from "./transactions/auth/index.js";

// Phase 6 — shared HL hierarchy primitive (271 / 277 / 277CA walkers).
export type { X12Hl } from "./transactions/shared/hl.js";

// Phase 3 — acknowledgments surface: parse / build 999 (005010X231A1) and
// envelope-level TA1 as pure functions. See `src/transactions/ack/index.ts`
// for the full barrel.
export {
  ACK_BUILD_ERROR_CODES,
  AckBuildError,
  IK3_SYNTAX_ERROR_CODES,
  IK4_SYNTAX_ERROR_CODES,
  TA1_ACK_CODES,
  TA1_NOTE_CODES,
  X12_ACK_DISPOSITION_CODES,
  build999,
  buildTA1,
  isAcceptDisposition,
  parse999,
  parseTA1,
  type AckBuildErrorCode,
  type Build999ElementErrorSpec,
  type Build999EnvelopeSpec,
  type Build999FunctionalGroupSpec,
  type Build999SegmentErrorSpec,
  type Build999Spec,
  type Build999TransactionResponseSpec,
  type BuildTA1Options,
  type BuildTA1Spec,
  type Ik304Code,
  type Ik403Code,
  type Ta1AckCode,
  type Ta1NoteCode,
  type X12Ack999,
  type X12Ack999Ak1,
  type X12Ack999Ak2,
  type X12Ack999Ak9,
  type X12Ack999ElementNote,
  type X12Ack999Ik3,
  type X12Ack999Ik4,
  type X12Ack999Ik4Position,
  type X12Ack999Ik5,
  type X12Ack999SegmentNote,
  type X12Ack999TransactionResponse,
  type X12AckDispositionCode,
  type X12AckTA1,
} from "./transactions/ack/index.js";

// Phase 8 — spec-clean serializer (the emit half of the parser).
export { serializeX12 } from "./serialize/index.js";
export type { SerializeOptions } from "./serialize/index.js";

// Phase 8 — general-purpose, segment-level interchange builder. The
// domain-specific builders (build835, build837P, …) layer on top of this.
export { buildInterchange, X12_BUILD_ERROR_CODES, X12BuildError } from "./builder/index.js";
export type {
  FunctionalGroupSpec,
  InterchangeSpec,
  SegmentSpec,
  TransactionSetSpec,
  X12BuildErrorCode,
} from "./builder/index.js";

// Phase 9 — trading-partner / companion-guide profile system. Built-ins are
// reached via the `profiles` namespace (not top-level), each grounded in a
// real Tier-2 fixture per the locked hard rule.
export {
  defineProfile,
  getDefaultProfile,
  partitionWarnings,
  profiles,
  setDefaultProfile,
  X12ProfileError,
} from "./profiles/index.js";
export type {
  X12Profile,
  X12ProfileDescription,
  X12ProfileEffect,
  X12ProfileQuirk,
  X12ProfileSpec,
  X12WarningPartition,
} from "./profiles/index.js";
